version: 2
updates:
  - package-ecosystem: pip
    directory: /adapter
    schedule: { interval: weekly }
  - package-ecosystem: pip
    directory: /submission_listener
    schedule: { interval: weekly }
  - package-ecosystem: pip
    directory: /submission_worker
    schedule: { interval: weekly }
  - package-ecosystem: pip
    directory: /get_history_worker
    schedule: { interval: weekly }
  - package-ecosystem: npm
    directory: /fabric-bridge
    schedule: { interval: weekly }
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
