#!/usr/bin/env python3
"""Derive minimal production lockfiles from the reviewed full component locks."""

from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
REQUIREMENT_RE = re.compile(r"^([A-Za-z0-9_.-]+)==")
RUNTIME_PACKAGES = {
    "submission_worker": {
        "certifi",
        "charset-normalizer",
        "idna",
        "pika",
        "python-dotenv",
        "requests",
        "urllib3",
    },
    "submission_listener": {
        "attrs",
        "certifi",
        "charset-normalizer",
        "idna",
        "jsonschema",
        "jsonschema-specifications",
        "pika",
        "pyjwt",
        "python-dotenv",
        "referencing",
        "requests",
        "rpds-py",
        "typing-extensions",
        "urllib3",
    },
}


def canonical(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def read_entries(path: Path) -> dict[str, list[str]]:
    entries: dict[str, list[str]] = {}
    lines = path.read_text(encoding="utf-8").splitlines()
    index = 0
    while index < len(lines):
        match = REQUIREMENT_RE.match(lines[index])
        if not match:
            index += 1
            continue
        name = canonical(match.group(1))
        block = [lines[index]]
        index += 1
        while index < len(lines) and lines[index].startswith((" ", "\t")):
            if "--hash=sha256:" in lines[index]:
                block.append(lines[index])
            index += 1
        entries[name] = block
    return entries


def generate(component_name: str, expected: set[str]) -> None:
    component = ROOT / component_name
    entries = read_entries(component / "requirements.lock")
    missing = sorted(expected - entries.keys())
    if missing:
        raise ValueError(f"{component_name}: missing runtime entries: {', '.join(missing)}")
    output = [
        "# Generated by scripts/security/generate_runtime_locks.py.",
        "# Source: the reviewed, hash-locked requirements.lock file.",
        "# Do not edit this file manually.",
        "",
    ]
    for name in sorted(expected):
        block = entries[name]
        if not any("--hash=sha256:" in line for line in block):
            raise ValueError(f"{component_name}: {name} has no SHA-256 hashes")
        output.extend(block)
    (component / "requirements.runtime.lock").write_text(
        "\n".join(output) + "\n", encoding="utf-8", newline="\n"
    )


def main() -> int:
    for component_name, expected in RUNTIME_PACKAGES.items():
        generate(component_name, expected)
    print(f"Generated {len(RUNTIME_PACKAGES)} production runtime lockfiles.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
