name: Test Submission Listener

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        cd submission_listener
        pip install -r requirements.txt
    
    - name: Run tests with coverage
      run: |
        cd submission_listener
        pytest --cov=app --cov-report=xml --cov-report=term-missing --cov-fail-under=75
    
    - name: Check coverage threshold
      run: |
        cd submission_listener
        python -c "
        import xml.etree.ElementTree as ET
        tree = ET.parse('coverage.xml')
        root = tree.getroot()
        coverage = float(root.attrib['line-rate']) * 100
        print(f'Coverage: {coverage:.2f}%')
        if coverage < 75:
            print('❌ Coverage below 75% threshold!')
            exit(1)
        else:
            print('✅ Coverage meets 75% threshold!')
        "
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./submission_listener/coverage.xml
        fail_ci_if_error: true

    - name: Upload coverage reports
      uses: actions/upload-artifact@v3
      with:
        name: coverage-reports
        path: |
          submission_listener/coverage.xml
          submission_listener/htmlcov/ 