name: Mock Peer Tests

on:
  push:
    paths:
      - 'mock_peer/**'
      - '.github/workflows/mock_peer_tests.yml'
  pull_request:
    paths:
      - 'mock_peer/**'
      - '.github/workflows/mock_peer_tests.yml'

jobs:
  test-mock-peer:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: mock_peer

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('mock_peer/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run mock_peer tests with coverage
      run: |
        timeout 60 pytest test_app.py -v --cov=app --cov-report=xml --cov-report=term-missing --cov-fail-under=80 || true