name: Submission Worker Tests

on:
   push:
    paths:
      - 'submission_worker/**'
      - '.github/workflows/submission_worker_tests.yml'
  pull_request:
    paths:
      - 'submission_worker/**'
      - '.github/workflows/submission_worker_tests.yml'
jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: submission_worker

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          pytest --cov --cov-report=xml

      - name: Upload coverage to GitHub Actions
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: submission_worker/coverage.xml

      - name: Enforce minimum coverage
        run: |
          coverage report --fail-under=80